//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SysFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class empleado
    {
        [Key]
        [DisplayName("Id del Empleado")]
        public int IdEmpleado { get; set; }

        [DisplayName("Nombre del Empleado")]
        [Required(ErrorMessage = "Nombre del Empleado es requerido.")]
        public string NombreEmpleado { get; set; }

        [DisplayName("Porciento de Comisión")]
        [Required(ErrorMessage = "Porciento de Comisión es requerido.")]
        public Nullable<decimal> PorcientoComision { get; set; }
        public string Estado { get; set; }
    }
}
